//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoUniversityCore.Infrastructure.TableauApi {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TableauRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableauRes() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContosoUniversityCore.Infrastructure.TableauApi.TableauRes", typeof(TableauRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge brute 2017.
        /// </summary>
        internal static string LMargeBrute {
            get {
                return ResourceManager.GetString("LMargeBrute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge brute sans tacite 2017.
        /// </summary>
        internal static string LMargeBruteSansTacite {
            get {
                return ResourceManager.GetString("LMargeBruteSansTacite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge brute 2017 - Semestre 1.
        /// </summary>
        internal static string LMargeBruteSem1 {
            get {
                return ResourceManager.GetString("LMargeBruteSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge brute 2017 - Semestre 2.
        /// </summary>
        internal static string LMargeBruteSem2 {
            get {
                return ResourceManager.GetString("LMargeBruteSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge brute 2017 - Semestre 3.
        /// </summary>
        internal static string LMargeBruteSem3 {
            get {
                return ResourceManager.GetString("LMargeBruteSem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017.
        /// </summary>
        internal static string LMargeExtreme {
            get {
                return ResourceManager.GetString("LMargeExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 1.
        /// </summary>
        internal static string LMargeExtremeSem1 {
            get {
                return ResourceManager.GetString("LMargeExtremeSem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 2.
        /// </summary>
        internal static string LMargeExtremeSem2 {
            get {
                return ResourceManager.GetString("LMargeExtremeSem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 3.
        /// </summary>
        internal static string LMargeExtremeSem3 {
            get {
                return ResourceManager.GetString("LMargeExtremeSem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 4.
        /// </summary>
        internal static string LMargeExtremeSem4 {
            get {
                return ResourceManager.GetString("LMargeExtremeSem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 5.
        /// </summary>
        internal static string LMargeExtremeSem5 {
            get {
                return ResourceManager.GetString("LMargeExtremeSem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 6.
        /// </summary>
        internal static string LMargeExtremeSem6 {
            get {
                return ResourceManager.GetString("LMargeExtremeSem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marge extrême sur année 2017 - Semaine 6 - Lundi.
        /// </summary>
        internal static string LMargeExtremeSem6Lundi {
            get {
                return ResourceManager.GetString("LMargeExtremeSem6Lundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre.
        /// </summary>
        internal static string Tableau1ColonneAutre {
            get {
                return ResourceManager.GetString("Tableau1ColonneAutre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Elec.
        /// </summary>
        internal static string Tableau1ColonneElec {
            get {
                return ResourceManager.GetString("Tableau1ColonneElec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gaz.
        /// </summary>
        internal static string Tableau1ColonneGaz {
            get {
                return ResourceManager.GetString("Tableau1ColonneGaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile.
        /// </summary>
        internal static string Tableau1ColonneProfile {
            get {
                return ResourceManager.GetString("Tableau1ColonneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TéléRelevé.
        /// </summary>
        internal static string Tableau1ColonneTeleReleve {
            get {
                return ResourceManager.GetString("Tableau1ColonneTeleReleve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        internal static string Tableau1ColonneTotal {
            get {
                return ResourceManager.GetString("Tableau1ColonneTotal", resourceCulture);
            }
        }
    }
}
